spring:
  datasource:
    url: jdbc:mysql://mysql_banking_app:3306/banking_core_db
    username: banking_user
    password: secure_banking_pwd_2024
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak_web:8080/realms/securebank-platform

keycloak:
  realm: securebank-platform
  auth-server-url: http://keycloak_web:8080
  ssl-required: external
  resource: securebank-api-client
  credentials:
    secret: your-client-secret
  use-resource-role-mappings: true
  bearer-only: true
