server:
  port: 8090

spring:
  application:
    name: banking-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yourusername/securebank-config-repo
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
        native:
          search-locations: classpath:/config
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
