version: '3.8'

services:
  mysql:
    build: ./mysql
    container_name: mysql_banking_app
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_root_pwd_2024
      - MYSQL_DATABASE=banking_core_db
      - MYSQL_USER=banking_user
      - MYSQL_PASSWORD=secure_banking_pwd_2024
    networks:
      banking_network:
        ipv4_address: 172.25.0.9
    ports:
      - "3306:3306"

  keycloak_postgre_db:
    image: postgres:latest
    container_name: keycloak_postgre_db
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak_admin
      - POSTGRES_PASSWORD=secure_keycloak_pwd_2024
    networks:
      banking_network:
        ipv4_address: 172.25.0.10

  keycloak:
    build: ./keycloak
    container_name: keycloak_auth
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgre_db:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_admin
      - KC_DB_PASSWORD=secure_keycloak_pwd_2024
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secure_admin_pwd_2024
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    networks:
      banking_network:
        ipv4_address: 172.25.0.11
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_postgre_db

networks:
  banking_network:
    ipam:
      config:
        - subnet: 172.25.0.0/16