server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: banking-user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_db
    username: banking_user
    password: secure_banking_pwd_2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      enabled: true
      uri: http://localhost:8090
      fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

keycloak:
  server-url: http://localhost:8080
  realm: securebank-platform
  client-id: securebank-kc-api-client
  client-secret: your-client-secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.securebank.user.controller
